export type {
  ExtractionResult,
  ExtractionStats,
  ExtractionRecord,
  SourcedValue,
  SourcedNumber,
  SourcedBoolean,
  Verfahrensdaten,
  Schuldner,
  Antragsteller,
  Forderungen,
  Gutachterbestellung,
  Ermittlungsergebnisse,
  Frist,
  Standardanschreiben,
  FehlendInfo,
  AnschreibenStatus,
  Pruefstatus,
} from '@shared/types/extraction';
